sylius_resource:
    resources:
        app.user:
            driver: doctrine/orm
            classes:
                model: AppBundle\Entity\User


fos_rest:
    disable_csrf_role: ROLE_API
    view:
        formats:
            json: true
    format_listener:
        rules:
            - { path: '^/api/', priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }
    routing_loader:
        default_format: json
        include_format: false
