app_user:
    resource: |
        alias: app.user
    type: sylius.resource_api

app_current_user_show:
    path: /user
    methods: [GET]
    defaults:
        _controller: app.controller.user:showAction
        _format: json
        _sylius:
            criteria: {id: 'expr:service("security.context").getToken().getUser().getId()'}

app_current_user_booking_index:
    path: /user/bookings/
    methods: [GET]
    defaults:
        _controller: app.controller.booking:indexAction
        _format: json
        _sylius:
            paginate: $limit
            criteria: { user: 'expr:service("security.context").getToken().getUser().getId()' }
            sortable: true

app_service_product:
    resource: |
        alias: app.service_product
    type: sylius.resource_api